upstream_dns: unbound
log_level: info
youtube_redirect_enabled: true
youtube_redirect_ip: ""
youtube_domains:
  - youtube.com
  - www.youtube.com
  - youtu.be
  - yt.be
  - m.youtube.com
captive_portal_enabled: false
captive_portal_ip: ""
rate_window: 10
rate_max: 100
burst_max_normal: 30
burst_max_iot: 10
block_duration: 300
