# Copyright (c) 2026 DownStreamTech (https://downstreamtech.net)
# Developed by: Richard R. Ayuyang, PhD
#               Professor II, CSU
# All rights reserved.

"""
Unbound DNS Settings — manage upstream resolvers, DNSSEC, cache, and
forwarding config via the Dashboard. Writes unbound.conf and reloads.
"""
import os

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import yaml

DOCKER_SOCK = "/var/run/docker.sock"
UNBOUND_CONTAINER = "richsinkhole-unbound-1"
UNBOUND_CONF = "/data/unbound.conf"
SETTINGS_PATH = "/data/unbound_settings.yml"

router = APIRouter()

# Well-known upstream DNS providers
UPSTREAM_PRESETS = {
    "quad9":      {"name": "Quad9 (Malware Blocking)",       "addrs": ["9.9.9.9", "149.112.112.112"]},
    "cloudflare": {"name": "Cloudflare",                     "addrs": ["1.1.1.1", "1.0.0.1"]},
    "google":     {"name": "Google Public DNS",              "addrs": ["8.8.8.8", "8.8.4.4"]},
    "opendns":    {"name": "OpenDNS (Cisco)",                "addrs": ["208.67.222.222", "208.67.220.220"]},
    "adguard":    {"name": "AdGuard DNS",                    "addrs": ["94.140.14.14", "94.140.15.15"]},
    "quad9_ecs":  {"name": "Quad9 (ECS, no malware filter)", "addrs": ["9.9.9.11", "149.112.112.11"]},
}

_DEFAULTS = {
    "upstreams": ["9.9.9.9", "149.112.112.112", "1.1.1.1", "1.0.0.1"],
    "dnssec": True,
    "cache_min_ttl": 60,
    "cache_max_ttl": 86400,
    "msg_cache_mb": 64,
    "rrset_cache_mb": 128,
    "prefetch": True,
    "qname_minimisation": True,
    "num_threads": 2,
}


def _load_settings() -> dict:
    try:
        with open(SETTINGS_PATH) as f:
            return {**_DEFAULTS, **yaml.safe_load(f)}
    except FileNotFoundError:
        return dict(_DEFAULTS)


def _save_settings(cfg: dict):
    with open(SETTINGS_PATH, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False)


def _generate_conf(cfg: dict) -> str:
    dnssec_block = """    auto-trust-anchor-file: "/var/lib/unbound/root.key"
    harden-dnssec-stripped: yes
    val-clean-additional: yes""" if cfg["dnssec"] else ""

    prefetch_block = f"""    prefetch: {"yes" if cfg["prefetch"] else "no"}
    prefetch-key: {"yes" if cfg["prefetch"] else "no"}"""

    upstreams = "\n".join(f"    forward-addr: {a}" for a in cfg["upstreams"])

    return f"""# Auto-generated by RichSinkhole Dashboard — do not edit manually
remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8953
    server-key-file: "/etc/unbound/unbound_server.key"
    server-cert-file: "/etc/unbound/unbound_server.pem"
    control-key-file: "/etc/unbound/unbound_control.key"
    control-cert-file: "/etc/unbound/unbound_control.pem"

server:
    interface: 0.0.0.0
    port: 53
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    access-control: 0.0.0.0/0 refuse
    access-control: 127.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 10.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow

    hide-identity: yes
    hide-version: yes
    identity: ""

{dnssec_block}

    harden-glue: yes
    harden-short-bufsize: yes
    harden-large-queries: yes
    harden-referral-path: no
    harden-algo-downgrade: yes
    use-caps-for-id: yes
    deny-any: yes
    harden-below-nxdomain: yes

    private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 127.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

    ratelimit: 1000
    ratelimit-size: 4m
    ratelimit-factor: 10
    ip-ratelimit: 1000
    ip-ratelimit-size: 4m

    qname-minimisation: {"yes" if cfg["qname_minimisation"] else "no"}
    qname-minimisation-strict: no

    cache-min-ttl: {cfg["cache_min_ttl"]}
    cache-max-ttl: {cfg["cache_max_ttl"]}
    neg-cache-size: 4m
    msg-cache-size: {cfg["msg_cache_mb"]}m
    rrset-cache-size: {cfg["rrset_cache_mb"]}m
    num-threads: {cfg["num_threads"]}
{prefetch_block}
    serve-expired: yes
    serve-expired-ttl: 3600
    aggressive-nsec: yes

    verbosity: 1
    log-queries: no
    log-replies: no

    do-not-query-localhost: yes
    minimal-responses: yes
    rrset-roundrobin: yes

forward-zone:
    name: "."
    forward-tls-upstream: no
{upstreams}
"""


async def _docker(method: str, path: str, **kwargs) -> httpx.Response:
    transport = httpx.AsyncHTTPTransport(uds=DOCKER_SOCK)
    async with httpx.AsyncClient(transport=transport, base_url="http://docker", timeout=30) as client:
        return await client.request(method, path, **kwargs)


async def _reload_unbound() -> bool:
    """Reload unbound config via Docker exec (unbound-control reload)."""
    if not os.path.exists(DOCKER_SOCK):
        return False
    try:
        # Create exec instance
        r = await _docker("POST", f"/containers/{UNBOUND_CONTAINER}/exec", json={
            "Cmd": ["unbound-control", "reload"],
            "AttachStdout": True,
            "AttachStderr": True,
        })
        if r.status_code != 201:
            return False
        exec_id = r.json()["Id"]
        # Start exec
        r2 = await _docker("POST", f"/exec/{exec_id}/start", json={"Detach": False})
        return r2.status_code == 200
    except Exception:
        return False


@router.get("/unbound/settings")
async def get_unbound_settings():
    cfg = _load_settings()
    return {
        "upstreams": cfg["upstreams"],
        "dnssec": cfg["dnssec"],
        "cache_min_ttl": cfg["cache_min_ttl"],
        "cache_max_ttl": cfg["cache_max_ttl"],
        "msg_cache_mb": cfg["msg_cache_mb"],
        "rrset_cache_mb": cfg["rrset_cache_mb"],
        "prefetch": cfg["prefetch"],
        "qname_minimisation": cfg["qname_minimisation"],
        "num_threads": cfg["num_threads"],
        "presets": UPSTREAM_PRESETS,
    }


class UnboundUpdate(BaseModel):
    upstreams: list[str] | None = None
    dnssec: bool | None = None
    cache_min_ttl: int | None = None
    cache_max_ttl: int | None = None
    msg_cache_mb: int | None = None
    rrset_cache_mb: int | None = None
    prefetch: bool | None = None
    qname_minimisation: bool | None = None
    num_threads: int | None = None


@router.post("/unbound/settings")
async def update_unbound_settings(body: UnboundUpdate):
    cfg = _load_settings()

    if body.upstreams is not None:
        # Validate IPs
        clean = [a.strip() for a in body.upstreams if a.strip()]
        if not clean:
            raise HTTPException(400, "At least one upstream DNS server required")
        cfg["upstreams"] = clean
    if body.dnssec is not None:
        cfg["dnssec"] = body.dnssec
    if body.cache_min_ttl is not None:
        cfg["cache_min_ttl"] = max(0, min(3600, body.cache_min_ttl))
    if body.cache_max_ttl is not None:
        cfg["cache_max_ttl"] = max(60, min(604800, body.cache_max_ttl))
    if body.msg_cache_mb is not None:
        cfg["msg_cache_mb"] = max(4, min(512, body.msg_cache_mb))
    if body.rrset_cache_mb is not None:
        cfg["rrset_cache_mb"] = max(4, min(512, body.rrset_cache_mb))
    if body.prefetch is not None:
        cfg["prefetch"] = body.prefetch
    if body.qname_minimisation is not None:
        cfg["qname_minimisation"] = body.qname_minimisation
    if body.num_threads is not None:
        cfg["num_threads"] = max(1, min(4, body.num_threads))

    _save_settings(cfg)

    # Write unbound.conf and reload
    conf = _generate_conf(cfg)
    with open(UNBOUND_CONF, "w") as f:
        f.write(conf)

    reloaded = await _reload_unbound()

    return {
        "status": "saved",
        "reloaded": reloaded,
        "message": "Settings saved" + (" and Unbound reloaded" if reloaded else ". Restart Unbound to apply."),
    }
